name: main
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  perl:
    env:
      # some plugins still needs this to run their tests...
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.40'
          - '5.38'
          - '5.36'
          - '5.34'
          - '5.32'
          - '5.30'
          - '5.28'
          - '5.26'
          - '5.24'
          - '5.22'
          - '5.20'
          - '5.18'
          - '5.16'
          - '5.14'
          - '5.12'
          - '5.10'

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
      options: --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0

    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - run: ip a
      - run: "[ -f /proc/net/if_inet6 ] && echo 'IPv6 ready system!' || echo 'No IPv6 support found! Compile the kernel!!'"
      - run: "lsmod | grep -qw ipv6 && echo 'IPv6 kernel driver loaded and configured.' || echo 'IPv6 not configured and/or driver loaded on the system.'"
      - run: modprobe ipv6
      - run: "lsmod | grep -qw ipv6 && echo 'IPv6 kernel driver loaded and configured.' || echo 'IPv6 not configured and/or driver loaded on the system.'"
      - run: sysctl -a | grep ipv6
      - name: Makefile.PL
        run: perl Makefile.PL
      - name: Install Dependencies
        run: cpm install -g --no-test --show-build-log-on-failure --cpanfile cpanfile
      - name: make test
        run: make test